name: Despliegue Manual y Verificación

on:
  workflow_dispatch:

jobs:
  check-system:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4  # <-- AQUÍ ESTABA EL ERROR, YA ESTÁ CORREGIDO

      - name: Levantar Odoo con Docker
        run: |
          docker compose up -d
          echo "Esperando a que Odoo y Postgres despierten..."
          sleep 20

      - name: Obtener IP para el Túnel
        run: |
          echo "---------------------------------------------------"
          echo "TU CONTRASEÑA (IP) PARA LOCALTUNNEL ES:"
          curl ifconfig.me
          echo -e "\n---------------------------------------------------"

      - name: Crear Túnel y Mantener Vivo
        run: |
          npm install -g localtunnel
          echo "---------------------------------------------------"
          echo "ABRE ESTA URL EN TU CELULAR:"
          echo "https://shadowroot-odoo.loca.lt"
          echo "---------------------------------------------------"
          lt --port 8069 --subdomain shadowroot-odoo & 
          echo "El servidor estará activo por 10 minutos."
          sleep 600

